lore/__init__.py, lore/stores/disk.py
Support 4GB pickles on linux when python > 3.4
Query cache can have very large results
@jeremystan
cc @rnaud
=> Lore 0.4.53

lore/transformers.py, tests/unit/test_transformers.py
A tranformer for age
Different units of time require standardization... e.g. is a month 28/30/31 days or dependent on the month?
@jeremystan 
cc @shiftb
=> Add an age transformer for consistent definitions across platforms

lore/encoders.py
Tags for encoders
`(Enum('column', tags={'foo'}), Enum('other', tags={'bar'})` allows annotating encoders to create subsets for different processing in pipelines and estimator layers.
@jeremystan 
cc @shiftb
=> Add tags to encoders

lore/estimators/keras.py
Default Sequence embed size to embed size instead of  defaulting to 10.
cc @montanalow @jeremystan  @theempiricist
=> Default sequence embedding size to embed size when not passed specifcally

README.rst
Making some of the mentions of external libs link to their sites/readmes.
Helps newbs who might be introduce to these things via lore.
----
If you like the gist of this, I'd be happy to go through for lots of other mentions and make them into links. (Of course not all READMEs need this treatment... I thought to do it here since `lore` has the admirable goal of making things more accessible to diverse audiences.)
Let me know?
=> [WIP] Minor README enhancement: External links for libraries

README.rst
Typo fix in the readthedocs link for XGBoost in README.rst
The link is currently broken because the scheme component of the URI is repeated (https://https://).
=> Fix typo in XGBoost readthedocs URL

lore/pipelines/holdout.py
Quick fix for `encoders`
Should use the private version from `get_encoder()`
=> small fix for multiprocess encoders

lore/estimators/holt_winters/__init__.py
Modify the import to resolve undefined names which may raise NameError at runtime.
flake8 testing of https://github.com/instacart/lore on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lore/env.py:291:32: F821 undefined name 'unicode'
config.readfp(StringIO(unicode(conf)))
^
./lore/estimators/holt_winters/__init__.py:23:15: F821 undefined name 'holtwinters'
results = holtwinters.additive(x, self.periodicity, self.forecasts,
^
./lore/estimators/holt_winters/__init__.py:33:12: F821 undefined name 'holtwinters'
return holtwinters.additive(X, self.periodicity, self.forecasts,
^
3     F821 undefined name 'unicode'
3
```
=> from lore.estimators.holt_winters.holtwinters import additive

lore/estimators/keras.py, tests/unit/test_models.py
Default kernel intiailizer for dense layer in keras is 'glorot_uniform'. But, many blogs/papers and even Andrew NG has been suggesting that using 'he_uniform' kernel initializer leads to faster and better convergence. There is even an exercise in deep learning course, where they show using 'he' initialization shows superior results. Keras already has support for it. This PR exposes setting that initializer in the estimator interface.
https://keras.io/initializers/#he_uniform
https://obilaniu6266h16.wordpress.com/2016/04/12/keras-he-adam-breakthrough/
=> Add support for kernel initializer during building estimator

lore/io/__init__.py
Fix file corruption in S3 upload
Because corruption is bad
=> Fix file corruption in S3 upload

lore/io/__init__.py
Fix issue where copying between different file systems breaks data retrieval.
Running lore from, e.g., a dedicated /home partition seems to cause trouble when data is being copied from /tmp to /home/path/to/app. An error with the following signature is raised (full traceback below): `OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpwl6lvhon' -> '/home/thomas/code/my_app/data/instacart_online_grocery_shopping_2017_05_01.tar.gz'`
`os.rename` only works if the source and destination path are on the same file system
Copying using `shutil.copy`, and subsequentially manually removing the source file fixes the issue.
Traceback:
```
$ lore fit my_app.models.product_popularity.Keras --test --score
FITTING my_app.models.product_popularity.Keras
[...]
11:21:36.644  ERROR    root:293 => …
```
=> Bugfix: Enable copying files between file systems

lore/estimators/__init__.py, lore/estimators/naive.py, lore/estimators/xgboost.py, lore/models/base.py, lore/models/naive.py, tests/mocks/models.py, tests/mocks/pipelines.py, tests/unit/test_models.py
- Create a naive estimator. A naive estimator is one that just returns the mean of the outcome variable.
- Support `predict_proba` on models if the underlying estimator allows it
- Add `predict_proba` method to xgboost to access probabilities
1. Naive models are useful for benchmarking
2. We should be able to access probabilities from classifiers when available
=> Create Naive Estimator

lore/estimators/sklearn.py
Add basic documentation and `predict_proba` to SKLearn Estimator
1. Documentation is good
2. Access to the `predict_proba` is not currently possible directly for sklearn estimators
=> Add basic documentation and `predict_proba` to SKLearn Estimator

lore/io/connection.py, tests/unit/io/test_connection.py, tests/unit/test_features.py
Check for snowflake.connector.errors.ProgrammingError while connecting to Snowflake from Lore. This is an indication that the user authentication token has expired and we need to get a new connection with valid user authentication token.
So, close the existing connection when this error happens and try to get a new connection to execute the query.
We are getting a lot of errors while connecting to Snowflake from lore because an existing connection has been idle for > 4 hours and we need to get a new user authentication token to query snowflake.
=> [Lore] Add exception handling for unauthenticated snowflake connections

lore/__main__.py, tests/mocks/tasks.py, tests/unit/test_main.py
Fix lore task command invocation.
```
$ lore task assignments.tasks.export.Predictions
File "~.pyenv/versions/3.6.6/envs/assignments/lib/python3.6/site-packages/lore/__main__.py", line 807, in task
print(ansi.success('RUNNING ') + task)
TypeError: must be str, not Predictions
```
It was broken.
=> Fix lore task invocation

README.rst
Fix a typo in README for a link.
=> Fix typo in README for XGBoost link

lore/io/connection.py
Stop logging data frame header and info by default but allow logging via a flag.
Even for the most basic queries this logging adds a base line 4-5ms per query.
```
➜  test git:(master) ✗ lore python sql_test.py
...
average runtime 2.0636 ms
```
```
➜  test git:(master) ✗ lore python sql_test.py
...
average runtime 6.25128 ms
```
```
import lore, lore.io
import time
import numpy as np
runtimes = []
main = lore.io.main
for item_id in range(0, 1000):
st = time.time()
results = main.dataframe(sql='select 1;')
runtime = round((time.time() - st)*1000.0, 2)
runtimes.append(runtime)
avg_runtime = np.mean(runtimes)
print("average runtime {} ms".format(avg_runtime))
```
=> Stop logging data frame header and info by default.

.circleci/config.yml, lore/dependencies.py, lore/io/__init__.py, lore/transformers.py, tests/unit/test_transformers.py
Fix tests by changing geoip DB url to be a private s3 url.
Fixes tests.
=> Marco fix geo ip test

release.sh
A script to do releases. Create git tags + upload to pypi.
It's just a helper so people don't have to lookup how to release everytime.
=> Add script to do releases.

.circleci/config.yml
Set postgres password in circleci container
CircleCI run is failing with
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".
You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password. This is *not* recommended. See PostgreSQL
documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
Exited with code 1
```
=> Fix CircleCI Build

lore/io/connection.py
Remove useless logging that is lighting our DD $ on fire.
We have a legacy service lighting money on fire and this is a stop gap until we can replace it in Q4/Q1. 
https://instacart.datadoghq.com/dashboard/n9r-94j-wwx/ads-infra-dashboard?fullscreen_end_ts=1663956214224&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1661364214224&fullscreen_widget=6719388726614565&from_ts=1664298847946&to_ts=1664302447946&live=true
Our lore service is hammering us on DD costs.
=> Remove useless logging
